server:
  port: 3333

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      
spring:
  application:
    name: customer-service
  data:
    mongodb:
      uri: mongodb://211.100.75.204/test