server:
  port: 2222

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
 
spring:
  application:
    name: account-service
  data:
    mongodb:
      uri: mongodb://211.100.75.204/test